project_name: rtc-utils
dist: dist

release:
  github:
    owner: TheCacophonyProject
    name: rtc-utils
  name_template: '{{.Tag}}'

builds:
- id: rtc
  binary: rtc
  main: ./cmd/rtc
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}

nfpms:
- vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cacophony Developers <coredev@cacophony.org.nz>
  description: Tools for managing the real-time clock
  license: GPL v3.0
  file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  contents:
    - src: _release/rtc.service
      dst: /etc/systemd/system/rtc.service
    - src: _release/rtc-ntp.service
      dst: /etc/systemd/system/rtc-ntp.service
    - src: _release/sync-rtc.cron
      dst: /etc/cron.hourly/sync-rtc
  scripts:
    postinstall: "_release/postinstall.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
